CREATE TABLE TEAMZ(
    TEAM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_NAME VARCHAR2(20)
);
CREATE TABLE TEAMW(
    MEM_ID VARCHAR2(20) PRIMARY KEY,
    TEAM_ID VARCHAR2(20),
    MEM_NAME VARCHAR2(20),
    MEM_AGE DECIMAL,
    ROLL VARCHAR2(20) --팀장, 팀원
);
ALTER TABLE TEAMW ADD CONSTRAINT teamw_fk_team_id FOREIGN KEY (TEAM_ID) REFERENCES TEAMZ(TEAM_ID);

INSERT INTO TEAMZ(
    TEAM_ID, TEAM_NAME
)
VALUES(
    'ATEAM','저스티스'
);
INSERT INTO TEAMZ(
    TEAM_ID, TEAM_NAME
)
VALUES(
    'HTEAM','엘카로'
);
INSERT INTO TEAMZ(
    TEAM_ID, TEAM_NAME
)
VALUES(
    'CTEAM','가오갤'
);
INSERT INTO TEAMZ(
    TEAM_ID, TEAM_NAME
)
VALUES(
    'STEAM','어벤저스'
);

INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '저스티스1', 'ATEAM', '형준', 34, '팀장'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '저스티스2', 'ATEAM', '세인', 35, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '저스티스3', 'ATEAM', '희태', 21, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '저스티스4', 'ATEAM', '상훈', 29, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '저스티스5', 'ATEAM', '태형', 25, '팀원'
);

INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '엘카로1', 'HTEAM', '혜리', 26, '팀장'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '엘카로2', 'HTEAM', '지은', 26, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '엘카로3', 'HTEAM', '준', 27, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '엘카로4', 'HTEAM', '재경', 30, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '엘카로5', 'HTEAM', '단아', 26, '팀원'
);

INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '가오갤1', 'CTEAM', '최정훈', 32, '팀장'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '가오갤2', 'CTEAM', '윤호', 31, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '가오갤3', 'CTEAM', '가은', 29, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '가오갤4', 'CTEAM', '정훈', 23, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '가오갤5', 'CTEAM', '승태', 30, '팀원'
);

INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '어벤저스1', 'STEAM', '승호', 27, '팀장'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '어벤저스2', 'STEAM', '소진', 26, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '어벤저스3', 'STEAM', '이슬', 29, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '어벤저스4', 'STEAM', '진태', 26, '팀원'
);
INSERT INTO TEAMW(
    MEM_ID, TEAM_ID, MEM_NAME, MEM_AGE, ROLL
)
VALUES(
    '어벤저스5', 'STEAM', '누리', 30, '팀원'
);
